name: 'cargo-bloat'
description: 'Track rust bloat across builds'
author: 'orf'
branding:
  icon: box
  color: blue
inputs:
  token:
    description: 'Github token to use'
    required: true
  kv_token:
    description: 'Kv token to use - saving snapshots'
    required: true
  bloat_args:
    description: 'Custom arguments to pass to cargo bloat'
    required: false
  by_function:
    description: 'If set, display per-function bloat instead of per-crate bloat.'
    required: false
  included_packages:
    description: 'Packages to include when running cargo bloat.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
